services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    restart: unless-stopped
    shm_size: '512m'
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
